version: "3.8"

services:

  app:
    build: .
    container_name: api
    # command: gunicorn core.wsgi:application --bind 0.0.0.0:8000


    # gunicorn core.wsgi:application --bind 0.0.0.0:8000
    # restart: always
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/staticfiles

    networks:
      - api_network

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app
    networks:
      - api_network
    volumes:
      - static_volume:/app/staticfiles


networks:
  api_network:
    driver: bridge


volumes:
  static_volume:
